GDB-3579 Manage repositories through GraphDBServerClient
Ontotext-AD/graphdb.js pull request #113
Opened 2021-01-04 14:21 UTC by teodossidossev

2021-01-05 08:35 UTC, svilenvelikov commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
Eventually describe these additional tasks in the readme

2021-01-05 08:37 UTC, teodossidossev commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
+1

2021-01-05 11:07 UTC, svilenvelikov commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
What does this `npm clean-install` do?

2021-01-05 11:11 UTC, svilenvelikov commented on src/http/client-config.js
> +      const credentials = `${this.username}:${this.pass}`;
We should account that `username` and `pass` can be missing here. Right?

2021-01-05 11:11 UTC, svilenvelikov commented on src/http/header-type.js
> +const HeaderType = {
These are media types and not header types.

2021-01-05 11:15 UTC, svilenvelikov commented on src/repository/repository-config-type.js
> +const RepositoryConfigType = {
These are also media types. Better merge them with the others which are currently in HeaderTypes

2021-01-05 11:17 UTC, svilenvelikov commented on src/security/authority-type.js
> +const AuthorityType = {
Maybe just `Authority` or `AuthorityRole`?

2021-01-05 11:21 UTC, svilenvelikov commented on src/server/app-settings.js
> +   * the Include inferred data in results option in the Workbench's SPARQL
We shouldn't mention the workbench anywhere as this client has nothing to do with it. It's just an sdk to be used with the GDB

2021-01-05 11:23 UTC, teodossidossev commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
This is the long name of ```npm ci``` - installs with a clean slate

2021-01-05 11:24 UTC, teodossidossev commented on src/http/client-config.js
> +      const credentials = `${this.username}:${this.pass}`;
Right!

2021-01-05 12:09 UTC, svilenvelikov commented on src/server/app-settings.js
> +   * the Include inferred data in results option in the Workbench's SPARQL
OK, turned out that these realy reflect the behavior in the workbench. The best is to untie the GDB API from the workbench API, but until then we mist boldly describe that these settings really can alter the behavior of the UI of the currently logged user.

2021-01-05 12:23 UTC, svilenvelikov commented on src/repository/repository-type.js
> +  FREE: 'free'
What about the `ontop` repo type?!

2021-01-05 12:35 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +  getRepositoryConfig(repositoryId, configType, location) {
This config is redundant for this API method. Better remove the parameter and also lines 67-69. This method should only realize the `GET /rest/repositories/{repositoryID}` API method. Repository config download is a separate method.

2021-01-05 12:37 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @private
Make this public

2021-01-05 12:57 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +  /**
uhmm what is this?

2021-01-05 13:54 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +  /**
It's a description of the fields of the ```RepositoryConfig``` object used in the ```createRepository``` method

2021-01-05 14:21 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @param {RepositoryConfig} repositoryConfig
There is no `RepositoryConfig` type. I suppose you mean `ClientConfig`.

2021-01-05 14:29 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @param {RepositoryConfig} repositoryConfig
I got the idea. You've defined the type above.. Technically it seems ok. I'll think about if it's not more appropriate if we define explictly a RepositoryConfig class for consistency, probably not. Will see.

2021-01-05 14:31 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @property {Object} [params] List of repository configuration parameters.
Well, technically it's not a list but an object or a map if you wish.

2021-01-05 14:48 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +          appSettings,
I think there is an issue here. Here you assume that appSettings is passed as a JSON object, which might not be the case. Especially when you defined the parameter as of AppSettings type. So, you either should check for the type and handle both cases or better expect the AppSettings type and call the toString method. Also you should update the tests as well.

2021-01-05 14:57 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @param {AppSettings} appSettings
As we spoke earlier, check if this configuration used here actually alters the behavior of the administrative interface (the workbench) and document it properly.

2021-01-05 14:58 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @param {AppSettings} appSettings
Same as for the createUser method. Check and document appSettings

2021-01-05 15:03 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +          password,
@desislava-hristova-ontotext I can't remember exactly, but as I see in the workbench, the password currently is sent as a plain text in a header. Right? This doesn't seem OK to me.

2021-01-05 15:18 UTC, svilenvelikov commented on test-e2e/package.json
> +    "axios": "^0.19.0",
Extract this in a separate MR please!

2021-01-05 15:21 UTC, svilenvelikov commented on test-e2e/tests/graphdb-server-client.spec.js
> +      return Utils.deleteRepo('Test_repo');
Add constant for this

2021-01-05 15:25 UTC, svilenvelikov commented on test-e2e/tests/graphdb-server-client.spec.js
> +    return serverClient.createRepository(config)
Maybe check for the available repositories first too in order to be sure that the test doesn't return false positives

2021-01-05 15:26 UTC, svilenvelikov commented on test-e2e/tests/graphdb-server-client.spec.js
> +  test('Should check ang toggle security repo', () => {
ang -> and

2021-01-05 15:30 UTC, svilenvelikov commented on test-e2e/tests/graphdb-server-client.spec.js
> +    const appSettings = {
As I mentioned in a comment in the GraphdbServerClient class, you probably need to work with the AppSettings class here, because currently you expect plain JSON object in the implementation and you actually don't test with the actual type

2021-01-05 15:32 UTC, svilenvelikov commented on test-e2e/tests/graphdb-server-client.spec.js
> +    const expextedAppSettings = {
Same note for the AppSettings as in the comments above

2021-01-05 15:33 UTC, svilenvelikov commented
I'm done with the review

2021-01-06 07:22 UTC, teodossidossev commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
added description

2021-01-06 07:22 UTC, teodossidossev commented on src/http/header-type.js
> +const HeaderType = {
renamed

2021-01-06 07:22 UTC, teodossidossev commented on src/repository/repository-config-type.js
> +const RepositoryConfigType = {
done

2021-01-06 07:22 UTC, teodossidossev commented on src/security/authority-type.js
> +const AuthorityType = {
renamed

2021-01-06 07:23 UTC, teodossidossev commented on src/repository/repository-type.js
> +  FREE: 'free'
added

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +  getRepositoryConfig(repositoryId, configType, location) {
done

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +   * @private
done

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +   * @property {Object} [params] List of repository configuration parameters.
fixed

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +          appSettings,
done

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +          authorities,
fixed

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +   * @param {AppSettings} appSettings
documented

2021-01-06 07:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +   * @param {AppSettings} appSettings
+1

2021-01-06 07:23 UTC, teodossidossev commented on test-e2e/package.json
> +    "axios": "^0.19.0",
ok

2021-01-06 07:24 UTC, teodossidossev commented on test-e2e/tests/graphdb-server-client.spec.js
> +      return Utils.deleteRepo('Test_repo');
done

2021-01-06 07:24 UTC, teodossidossev commented on test-e2e/tests/graphdb-server-client.spec.js
> +    return serverClient.createRepository(config)
done

2021-01-06 07:24 UTC, teodossidossev commented on test-e2e/tests/graphdb-server-client.spec.js
> +  test('Should check ang toggle security repo', () => {
+1

2021-01-06 07:24 UTC, teodossidossev commented on test-e2e/tests/graphdb-server-client.spec.js
> +    const appSettings = {
done

2021-01-06 07:24 UTC, teodossidossev commented on test-e2e/tests/graphdb-server-client.spec.js
> +    const expextedAppSettings = {
+1

2021-01-06 09:36 UTC, svilenvelikov requested changes

2021-01-06 09:36 UTC, svilenvelikov commented on README.md
> + const appSettings = {
Change this to use the class

2021-01-06 09:36 UTC, svilenvelikov commented on package.json
> +    "install:e2e": "cd test-e2e/ && npm clean-install && npm link graphdb",
and why don't use the `npm ci` then? :)

2021-01-06 09:36 UTC, svilenvelikov commented on src/http/client-config.js
> +      const credentials = `${this.username}:${this.pass}`;
And what about this? Maybe add some check and throw error

2021-01-06 09:36 UTC, svilenvelikov commented on src/http/media-type.js
> +  TURTLE: 'text/turtle'
follow the pattern: `TEXT_TURTLE`

2021-01-06 09:36 UTC, svilenvelikov commented on src/server/app-settings.js
> +    this.defaultSameas = defaultSameas;
`return this` and also update the jsdoc too

2021-01-06 09:36 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +   * @param {RepositoryConfig} repositoryConfig
At the end, I prefer we to have a class for this config similarly to all other configs we have in order to make it more explicit.

2021-01-06 09:36 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +          appSettings: appSettings && appSettings.toString() || {}
maybe add a method for this appSettings resolving

2021-01-06 13:04 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +          appSettings: appSettings && appSettings.toString() || {}
done

2021-01-06 13:04 UTC, teodossidossev commented on src/server/app-settings.js
> +    this.defaultSameas = defaultSameas;
done

2021-01-06 13:04 UTC, teodossidossev commented on src/http/media-type.js
> +  TURTLE: 'text/turtle'
ok

2021-01-06 13:04 UTC, teodossidossev commented on README.md
> + const appSettings = {
ok

2021-01-06 13:04 UTC, teodossidossev commented on README.md
> +  const config = {
done

2021-01-06 13:04 UTC, teodossidossev commented on README.md
> + serverClient.downloadRepositoryConfig('Test_repo').then((response) => {
done

2021-01-06 13:04 UTC, teodossidossev commented on README.md
> +  return serverClient.updateUserData('test_user', '111222', newAppSettings);
done

2021-01-06 13:04 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +   * @param {RepositoryConfig} repositoryConfig
done

2021-01-06 14:02 UTC, svilenvelikov commented on src/repository/repository-config.js
> +  toString() {
let this be `toJson` because we actually don't serialize to string here

2021-01-06 14:04 UTC, svilenvelikov commented on src/server/app-settings.js
> +  toString() {
let this be `toJson` because we actually don't serialize to string here

2021-01-06 14:05 UTC, svilenvelikov commented on src/server/graphdb-server-client.js
> +  getObjectToString(object) {
make it `objectToJson(object)`

2021-01-06 14:22 UTC, teodossidossev commented on src/server/app-settings.js
> +  toString() {
+1

2021-01-06 14:22 UTC, teodossidossev commented on src/repository/repository-config.js
> +  toString() {
+1

2021-01-06 14:23 UTC, teodossidossev commented on src/server/graphdb-server-client.js
> +  getObjectToString(object) {
+1

2021-01-06 14:35 UTC, svilenvelikov approved these changes

2021-01-06 14:39 UTC, merged