GDB-5393 Refactor repository and server clients configuration
Ontotext-AD/graphdb.js pull request #127
Opened 2021-01-25 13:01 UTC by teodossidossev

Provides configuration builder and unifies configuration creation.

2021-01-26 09:29 UTC, svilenvelikov commented on src/http/client-config-builder.js
> +  static serverConfig(endpoint) {
Remove the `static` in order to be consistent with other methods.

2021-01-26 09:32 UTC, svilenvelikov commented on src/http/client-config-builder.js
> +  static serverConfig(endpoint) {
Or maybe make the other two `private`

2021-01-26 11:50 UTC, teodossidossev commented on src/http/client-config-builder.js
> +  static serverConfig(endpoint) {
Both creator methods are static to be consistent with the other builders in the driver.

2021-01-26 11:58 UTC, svilenvelikov requested changes

2021-01-26 11:58 UTC, svilenvelikov commented on test-e2e/tests/config.js
> +/* eslint-disable max-len */
Can't you just format the line instead?!

2021-01-26 11:58 UTC, svilenvelikov commented on test-e2e/tests/auth-server-client.spec.js
> +/* eslint "require-jsdoc": off*/
Better just exclude the rule for the tests. See https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

2021-01-26 11:58 UTC, svilenvelikov commented on src/http/client-config.js
> +    this.useBasicAuthentication();
Also `setBasicAuthentication` does the same and I think it's not correct to have a setter which does something else underneath. IMO this basic auth configration should be made explicit and should not make the user wonder how to configure the client. Think if it wouldn't be better to remove the user/pass setters in favor of `useBasicAuthentication` which should also require the user/pass as arguments and does all this explicit.

2021-01-26 11:58 UTC, svilenvelikov commented on test/repository/rdf-repository-client-adding-data.spec.js
> +/* eslint "require-jsdoc": off*/
remove these: format the long lines and disable the jsdoc rule for tests

2021-02-09 08:43 UTC, svilenvelikov requested changes

2021-02-09 08:43 UTC, svilenvelikov commented on src/server/server-client.js
> +        this.setLoggedUser(user);
You execute a login with logged user and after that you set logged user... it's strange. Is the user logged in before login execution and what does it happend with it after the login?

2021-02-09 08:43 UTC, svilenvelikov commented on src/server/server-client.js
> +  getLoggedUser() {
Why not just `getUser` and `setUser`? Otherwise it's confusing.

2021-02-09 08:43 UTC, svilenvelikov commented on src/service/authentication-service.js
> +   * @return {BasicAuthentication|GdbTokenAuthentication} conctrete
typo in `conctrete`

2021-02-09 08:43 UTC, svilenvelikov commented on src/service/transaction-service.js
> +      .repositoryConfig(config.getEndpoint())
Here's an example of why the `ClientConfigBuilder` is confusing. You get an instance of the `RepositoryClientConfig` builder by just providing the only required parameter and then continue with its initialization. It's seems just redundant to me.

2021-02-09 08:43 UTC, svilenvelikov commented on test/repository/rdf-repository-client-query.spec.js
> +    const expectedData = 'query=select%20*%20where%20%7B%3Fs%20%3Fp%20%3Fo%7D' +
pff this formatting in the tests was quite unneeded IMO

2021-02-09 13:47 UTC, svilenvelikov approved these changes

2021-02-10 07:17 UTC, svilenvelikov approved these changes

2021-02-10 07:55 UTC, svilenvelikov approved these changes

2021-02-10 08:03 UTC, merged